version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: name
    volumes:
      - test-data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - '6379:6379'
    restart: always

  admin:
    image: adminer
    restart: always
    ports:
      - 9999:8080

volumes:
  test-data:
